 baseURL = "https://www.AdamMedford.com/"
# baseURL = "localhost:3000/"
title = "adam medford"
theme = "temple"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = "(c) 2018 - 2019"

[params]
  # Enables syntax highlighting
  highlight = true 

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Adam Medford"
  github = "adammedford"
  email = "adammedford@gmail.com"
  gaid = "UA-72408800-1"
  #twitter = "twitterID"
  #medium = "mediumUsername"

[permalinks]
  posts = "/:year/:month/:title/"
